# file: s3fs/tasks/main.yml
---

  - command: "which s3fs"
    register: s3_exists
    ignore_errors: True

  - name: install prequisites
    sudo: yes
    apt: "pkg={{ item }} state=present"
    with_items:
      - build-essential
      - libfuse-dev
      - libcurl4-openssl-dev
      - libxml2-dev
      - mime-support
      - unzip
      - autoconf
    when: s3_exists|failed

  - name: "copy src"
    copy: 
      src: "s3fs-{{ s3fs_version }}.tar.gz"
      dest: "/tmp/s3fs-{{ s3fs_version }}.tar.gz"
      mode: 0644

  - name: "copy password"
    copy:
      src: "{{ s3fs_aws_key }}"
      dest: /etc/passwd-s3fs
      mode: 0600
    sudo: yes
    when: s3fs_aws_key is defined

  - name: extract
    unarchive: 
      src: "/tmp/s3fs-{{ s3fs_version }}.tar.gz"
      dest: /tmp
      copy: no
    when: s3_exists|failed

  - name: "configure & build"
    sudo: yes
    command: "{{ item }} chdir='/tmp/s3fs-{{ s3fs_version }}'"
    with_items:
      - autoreconf --install
      - ./configure --prefix=/usr
      - make
      - make install
    when: s3_exists|failed

  - name: create mount point
    sudo: yes
    file: "path={{ item.mount }} state=directory"
    when: s3_exists|failed
    with_items: s3fs_mounts

  - name: mount the bucket
    sudo: yes
    command: s3fs {{ item.bucket }} -o use_cache=/tmp -o allow_other {{ item.mount }}
    when: s3_exists|failed
    with_items: s3fs_mounts
